#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="${ROOT:-$(cd -- "$SCRIPT_DIR/.." && pwd)}"
PY="${PY:-python}"
METHOD="${METHOD:-}"
DATASET="${DATASET:-}"
STRIDE="${STRIDE:-}"
TUM_MODE="${TUM_MODE:-full}"
ALIGN="${ALIGN:-}"
CKPT="${CKPT:-}"
GPU="${GPU:-0}"
OUT_DIR="${OUT_DIR:-}"
RUN_NAME="${RUN_NAME:-}"
ROT_CORRECTION_MODE="${ROT_CORRECTION_MODE:-causal_conv}"
ROT_CORRECTION_KERNEL="${ROT_CORRECTION_KERNEL:-10}"
LINGBOT_MAX_FRAMES="${LINGBOT_MAX_FRAMES:-8000}"
OFFICIAL_ROOT="${OFFICIAL_ROOT:-$ROOT/third_party}"
LINGBOT_ROOT="${LINGBOT_ROOT:-$OFFICIAL_ROOT/LingBot-Map}"
HS_ROOT="${HS_ROOT:-$ROOT/third_party/HorizonStream}"
HORIZON_AMP_DTYPE="${HORIZON_AMP_DTYPE:-fp16}"
ATTENTION_BACKEND="${ATTENTION_BACKEND:-paged}"
ROPE2D_BACKEND="${ABOT_RECON_ROPE2D_BACKEND:-cuda}"
STREAM3R_CHUNK_SIZE="${STREAM3R_CHUNK_SIZE:-1}"
SEQ_NAMES="${SEQ_NAMES:-}"
SAVE_PLY="${SAVE_PLY:-false}"
SAVE_PLY_SEQS="${SAVE_PLY_SEQS:-}"
SAVE_TRAJ_BEV="${SAVE_TRAJ_BEV:-false}"
REBUILD_SEQ_MAP="${REBUILD_SEQ_MAP:-false}"
F1_THRESHOLDS="${F1_THRESHOLDS:-}"
DRY_RUN="${DRY_RUN:-false}"
CONFIG_CHECK="${CONFIG_CHECK:-false}"
MAX_EVAL_FRAMES="${MAX_EVAL_FRAMES:-0}"
ALIGNMENT_DEPTH_MAX="${ALIGNMENT_DEPTH_MAX:-}"
CHECKPOINT_SHA256="${FORMAL_CHECKPOINT_SHA256:-}"
OXFORD_METRIC_INTERVAL="${OXFORD_METRIC_INTERVAL:-10}"

usage() {
  cat <<'EOF'
Run one point-cloud evaluation protocol.

Required:
  --method abot_recon|lingbot|horizon|cut3r|ttt3r|longstream|infinitevggt|ovggt|stream3r_window5
  --dataset 7scenes|oxford|tum
  --out-dir PATH

Sampling:
  --stride 1               Formal protocols are stride 1
  --tum-mode full          TUM-Dynamics-Full only
  --oxford-metric-interval N
                           Oxford TLS metric interval (default: 10; the formal
                           technical-report protocol requires 10)

Model/alignment:
  --ckpt PATH              Required model checkpoint
  --align sim3|se3         Formal default: Sim3 for every method
  --rot-correction-mode causal_conv|none  ABot-Recon only
  --rot-correction-kernel N               ABot-Recon causal-conv kernel
  --attention-backend auto|paged|sdpa  ABot-Recon; auto prefers paged FlashInfer
  --hs-root PATH           HorizonStream source tree
  --horizon-amp-dtype auto|bf16|fp16|fp32
                           Horizon forward precision (formal default: fp16)
  --official-root PATH     Clean official checkout root for added baselines
  --lingbot-root PATH      LingBot-Map source tree
  --stream3r-chunk-size N  RGB chunk size (default: 1); stream3r_window5 is
                           reported as native world-points, not depth+K

Runtime/output:
  --gpu INDEX              Physical GPU exposed as cuda:0 (default: 0)
  --run-name NAME          Output slug; generated by default
  --seq-names '[a,b]'      Optional manual sequence shard
  --max-eval-frames N      Limit each sequence for smoke tests (0 = all)
  --alignment-depth-max M  Pred-camera depth cutoff for Umeyama only; metrics
                           still score all valid prediction points
  --save-ply true|false    Default: false
  --save-ply-seqs '[a,b]'  Save qualitative PLYs only for these sequences;
                           implies --save-ply true
  --save-traj true|false   Default: true
  --rebuild-seq-map true|false
  --dry-run                Print the resolved command without running it
  --config-check           Compose and resolve Hydra config, without inference

Protocol mapping:
  7Scenes stride1 -> seven <scene>/seq-01 sequences, F1 primary 0.25 m
  Oxford stride1  -> all ten rectified sequences; all frames are forwarded,
                     TLS point-cloud metrics use frame_ids 0,10,20,... and
                     report F1@2m/4m (primary 4m)
  TUM mode full   -> TUM-Dynamics-Full (all associated RGB frames)

Indoor protocols compute F1@0.05/0.25; Oxford computes F1@2/4m.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --method) METHOD="$2"; shift 2 ;;
    --dataset) DATASET="$2"; shift 2 ;;
    --stride) STRIDE="$2"; shift 2 ;;
    --tum-mode) TUM_MODE="$2"; shift 2 ;;
    --oxford-metric-interval) OXFORD_METRIC_INTERVAL="$2"; shift 2 ;;
    --align) ALIGN="$2"; shift 2 ;;
    --ckpt) CKPT="$2"; shift 2 ;;
    --gpu) GPU="$2"; shift 2 ;;
    --out-dir) OUT_DIR="$2"; shift 2 ;;
    --run-name) RUN_NAME="$2"; shift 2 ;;
    --rot-correction-mode) ROT_CORRECTION_MODE="$2"; shift 2 ;;
    --rot-correction-kernel) ROT_CORRECTION_KERNEL="$2"; shift 2 ;;
    --lingbot-max-frames) LINGBOT_MAX_FRAMES="$2"; shift 2 ;;
    --hs-root) HS_ROOT="$2"; shift 2 ;;
    --horizon-amp-dtype) HORIZON_AMP_DTYPE="$2"; shift 2 ;;
    --attention-backend) ATTENTION_BACKEND="$2"; shift 2 ;;
    --official-root) OFFICIAL_ROOT="$2"; shift 2 ;;
    --lingbot-root) LINGBOT_ROOT="$2"; shift 2 ;;
    --stream3r-chunk-size) STREAM3R_CHUNK_SIZE="$2"; shift 2 ;;
    --seq-names) SEQ_NAMES="$2"; shift 2 ;;
    --max-eval-frames) MAX_EVAL_FRAMES="$2"; shift 2 ;;
    --alignment-depth-max) ALIGNMENT_DEPTH_MAX="$2"; shift 2 ;;
    --save-ply) SAVE_PLY="$2"; shift 2 ;;
    --save-ply-seqs) SAVE_PLY_SEQS="$2"; shift 2 ;;
    --save-traj) SAVE_TRAJ_BEV="$2"; shift 2 ;;
    --rebuild-seq-map) REBUILD_SEQ_MAP="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --config-check) CONFIG_CHECK=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

die() { echo "ERROR: $*" >&2; exit 2; }
is_bool() { [[ "$1" == true || "$1" == false ]]; }

[[ -n "$METHOD" ]] || die "--method is required"
[[ -n "$DATASET" ]] || die "--dataset is required"
[[ -n "$OUT_DIR" ]] || die "--out-dir is required"
[[ "$METHOD" =~ ^(abot_recon|lingbot|horizon|cut3r|ttt3r|longstream|infinitevggt|ovggt|stream3r_window5)$ ]] || die "invalid method: $METHOD"
[[ "$DATASET" =~ ^(7scenes|oxford|tum)$ ]] || die "invalid dataset: $DATASET"
is_bool "$SAVE_PLY" || die "--save-ply must be true or false"
if [[ -n "$SAVE_PLY_SEQS" ]]; then
  SAVE_PLY=true
fi
is_bool "$SAVE_TRAJ_BEV" || die "--save-traj must be true or false"
is_bool "$REBUILD_SEQ_MAP" || die "--rebuild-seq-map must be true or false"
[[ "$MAX_EVAL_FRAMES" =~ ^[0-9]+$ ]] || die "--max-eval-frames must be a non-negative integer"
[[ "$OXFORD_METRIC_INTERVAL" =~ ^[1-9][0-9]*$ ]] || die "--oxford-metric-interval must be a positive integer"
[[ "$HORIZON_AMP_DTYPE" =~ ^(auto|bf16|fp16|fp32)$ ]] || die "--horizon-amp-dtype must be auto, bf16, fp16, or fp32"
[[ "$ATTENTION_BACKEND" =~ ^(auto|paged|sdpa)$ ]] || die "--attention-backend must be auto, paged, or sdpa"
[[ "$ROPE2D_BACKEND" =~ ^(auto|cuda|torch)$ ]] || die "invalid ABOT_RECON_ROPE2D_BACKEND"

if [[ -z "$ALIGN" ]]; then
  ALIGN=sim3
fi
[[ "$ALIGN" =~ ^(sim3|se3)$ ]] || die "--align must be sim3 or se3"
if [[ "$ALIGN" == sim3 ]]; then
  WITH_SCALE=true
else
  WITH_SCALE=false
fi

case "$DATASET" in
  7scenes)
    [[ -z "$STRIDE" || "$STRIDE" == 1 ]] || die "formal 7Scenes --stride must be 1"
    STRIDE=1
    EVAL_CFG=mv_recon_7scenes
    DATA_KEY=7scenes-hs-paper
    PROTOCOL_TAG=7s_seq01_s1
    PRIMARY_THRESHOLD=0.25
    [[ -n "$F1_THRESHOLDS" ]] || F1_THRESHOLDS='[0.05,0.25]'
    ;;
  oxford)
    [[ -z "$STRIDE" || "$STRIDE" == 1 ]] || die "Oxford --stride must be 1"
    [[ "$OXFORD_METRIC_INTERVAL" == 10 ]] ||
      die "formal Oxford protocol requires --oxford-metric-interval 10"
    STRIDE=1
    EVAL_CFG=mv_recon_oxford_stride1
    DATA_KEY=Oxford-Spires-S1-I10
    PROTOCOL_TAG=oxford_s1_i10
    PRIMARY_THRESHOLD=4.0
    [[ -n "$F1_THRESHOLDS" ]] || F1_THRESHOLDS='[2.0,4.0]'
    ;;
  tum)
    [[ "$TUM_MODE" == full ]] || die "formal TUM --tum-mode must be full"
    STRIDE=1
    EVAL_CFG=mv_recon_tum_full
    DATA_KEY=TUM-Dynamics-Full
    PROTOCOL_TAG=tum_full_s1
    PRIMARY_THRESHOLD=0.25
    [[ -n "$F1_THRESHOLDS" ]] || F1_THRESHOLDS='[0.05,0.25]'
    ;;
esac

case "$METHOD" in
  abot_recon) MODEL_KEY=abot_recon ;;
  lingbot) MODEL_KEY=lingbot_map ;;
  horizon) MODEL_KEY=horizonstream ;;
  *) MODEL_KEY=$METHOD ;;
esac
MODEL_CFG=default

[[ -n "$CKPT" ]] || die "--ckpt is required for $METHOD"
command -v "$PY" >/dev/null || die "python is not executable: $PY"
[[ -d "$ROOT" ]] || die "evaluation root does not exist: $ROOT"
[[ -e "$CKPT" ]] || die "checkpoint does not exist: $CKPT"
if [[ "$METHOD" == horizon ]]; then
  [[ -d "$HS_ROOT" ]] || die "HorizonStream root does not exist: $HS_ROOT"
fi
if [[ "$METHOD" =~ ^(cut3r|ttt3r|longstream|infinitevggt|ovggt|stream3r_window5)$ ]]; then
  [[ -d "$OFFICIAL_ROOT" ]] || die "official checkout root does not exist: $OFFICIAL_ROOT"
fi

if [[ -z "$RUN_NAME" ]]; then
  RUN_NAME=${METHOD}_${PROTOCOL_TAG}_${ALIGN}
fi
mkdir -p "$OUT_DIR" "$OUT_DIR/hydra"

CMD=(
  "$PY" mv_recon/eval.py
  "evaluation=$EVAL_CFG"
  "model=$MODEL_CFG"
  "eval_models=[$MODEL_KEY]"
  "eval_datasets=[$DATA_KEY]"
  "kf_every=$STRIDE"
  "++pc_align_with_scale=$WITH_SCALE"
  "++pc_eval_threshold=$PRIMARY_THRESHOLD"
  "++pc_eval_thresholds=$F1_THRESHOLDS"
  "pointmap_resize_mode=nearest"
  "pi3_pc_world_source=points"
  "abot_recon_loop_enabled=false"
  "save_ply=$SAVE_PLY"
  "save_traj_bev=$SAVE_TRAJ_BEV"
  "++require_runtime_manifest=true"
  "++strict_pointcloud_protocol=true"
  "rebuild_seq_id_map=$REBUILD_SEQ_MAP"
  "++max_eval_frames=$MAX_EVAL_FRAMES"
  "++save_suffix=$RUN_NAME"
  "name=$RUN_NAME"
  "output_dir=$OUT_DIR"
  "hydra.run.dir=$OUT_DIR/hydra"
)

if [[ "$DATASET" == oxford ]]; then
  CMD+=("data.$DATA_KEY.cfg.expected_interval=$OXFORD_METRIC_INTERVAL")
fi

if [[ -n "$SAVE_PLY_SEQS" ]]; then
  CMD+=("++save_ply_seq_names=$SAVE_PLY_SEQS")
fi

if [[ -n "$SEQ_NAMES" ]]; then
  CMD+=("+eval_seq_names=$SEQ_NAMES")
fi
if [[ -n "$ALIGNMENT_DEPTH_MAX" ]]; then
  CMD+=("++pc_alignment_depth_max=$ALIGNMENT_DEPTH_MAX")
fi

case "$METHOD" in
  abot_recon|abot_recon)
    CMD+=(
      "model.abot_recon.cfg.ckpt=$CKPT"
      "model.abot_recon.cfg.attention_backend=$ATTENTION_BACKEND"
      "model.abot_recon.eval_output_name=$RUN_NAME"
    )
    ;;
  lingbot)
    CMD+=(
      "model.lingbot_map.cfg.pretrained_model_name_or_path=$CKPT"
      "model.lingbot_map.cfg.source_root=$LINGBOT_ROOT"
      "model.lingbot_map.cfg.max_frame_num=$LINGBOT_MAX_FRAMES"
    )
    ;;
  horizon)
    CMD+=(
      "model.horizonstream.cfg.checkpoint=$CKPT"
      "model.horizonstream.cfg.horizonstream_root=$HS_ROOT"
      "model.horizonstream.cfg.amp_dtype=$HORIZON_AMP_DTYPE"
      "model.horizonstream.cfg.strict_load=true"
    )
    ;;
  cut3r|ttt3r)
    CMD+=(
      "model.$METHOD.cfg.pretrained_model_name_or_path=$CKPT"
      "model.$METHOD.cfg.source_root=$OFFICIAL_ROOT/${METHOD^^}"
      "model.$METHOD.cfg.input_size=512"
    )
    ;;
  longstream)
    CMD+=(
      "model.longstream.cfg.checkpoint=$CKPT"
      "model.longstream.cfg.source_root=$OFFICIAL_ROOT/LongStream"
    )
    ;;
  infinitevggt)
    CMD+=(
      "model.infinitevggt.cfg.checkpoint=$CKPT"
      "model.infinitevggt.cfg.source_root=$OFFICIAL_ROOT/InfiniteVGGT"
    )
    ;;
  ovggt)
    CMD+=(
      "model.ovggt.cfg.checkpoint=$CKPT"
      "model.ovggt.cfg.source_root=$OFFICIAL_ROOT/OVGGT"
    )
    ;;
  stream3r_window5)
    CMD+=(
      "model.$METHOD.cfg.checkpoint=$CKPT"
      "model.$METHOD.cfg.source_root=$OFFICIAL_ROOT/STream3R"
      "model.$METHOD.cfg.chunk_size=$STREAM3R_CHUNK_SIZE"
    )
    ;;
esac

echo "method=$METHOD dataset=$DATA_KEY protocol=$PROTOCOL_TAG stride=$STRIDE align=$ALIGN"
echo "gpu=$GPU output=$OUT_DIR"
if [[ "$METHOD" =~ ^(abot_recon|abot_recon)$ ]]; then
  export ABOT_RECON_ROPE2D_BACKEND="$ROPE2D_BACKEND"
fi
printf 'command: CUDA_VISIBLE_DEVICES=%q ' "$GPU"
printf '%q ' "${CMD[@]}"
printf '\n'

if [[ "$DRY_RUN" == true ]]; then
  exit 0
fi

cd "$ROOT"
export CUDA_VISIBLE_DEVICES="$GPU"
if [[ "$CONFIG_CHECK" == true ]]; then
  exec "${CMD[@]}" --cfg job --resolve
fi

case "$METHOD" in
  abot_recon|abot_recon) MODEL_REPO_ROOT="$ROOT" ;;
  # LingBotMAP is imported from an external LingBot-Map checkout by models.fastmodel.
  # Derive provenance from that same rule; an unrelated environment override
  # must not claim that a different checkout was executed.
  lingbot) MODEL_REPO_ROOT="$(readlink -f "$ROOT/../../lingbot-map")" ;;
  horizon) MODEL_REPO_ROOT="$HS_ROOT" ;;
  cut3r|ttt3r|longstream|infinitevggt|ovggt|stream3r_window5)
    case "$METHOD" in
      cut3r|ttt3r) MODEL_REPO_ROOT="$OFFICIAL_ROOT/${METHOD^^}" ;;
      longstream) MODEL_REPO_ROOT="$OFFICIAL_ROOT/LongStream" ;;
      infinitevggt) MODEL_REPO_ROOT="$OFFICIAL_ROOT/InfiniteVGGT" ;;
      ovggt) MODEL_REPO_ROOT="$OFFICIAL_ROOT/OVGGT" ;;
      stream3r_window5) MODEL_REPO_ROOT="$OFFICIAL_ROOT/STream3R" ;;
    esac
    ;;
esac
printf -v COMMAND_TEXT 'CUDA_VISIBLE_DEVICES=%q ' "$GPU"
printf -v COMMAND_ARGS '%q ' "${CMD[@]}"
COMMAND_TEXT+="$COMMAND_ARGS"
META=(
  "$PY" "$ROOT/scripts/formal_run_metadata.py" start
  --out-dir "$OUT_DIR"
  --eval-root "$ROOT"
  --model-root "$MODEL_REPO_ROOT"
  --checkpoint "$CKPT"
  --command "$COMMAND_TEXT"
)
if [[ -n "$CHECKPOINT_SHA256" ]]; then
  META+=(--checkpoint-sha256 "$CHECKPOINT_SHA256")
fi
"${META[@]}"
set +e
"${CMD[@]}"
rc=$?
set -e
printf '%s\n' "$rc" > "$OUT_DIR/exit_code.txt"
if [[ $rc -ne 0 ]]; then
  exit "$rc"
fi
"$PY" "$ROOT/scripts/formal_run_metadata.py" finish --out-dir "$OUT_DIR"
